/** UN M49 Europe plus Kosovo, Cyprus, and Türkiye. United Kingdom is GB (ISO), with reserved UK. */

export type EuropeanCountry = {
  /** ISO 3166-1 alpha-2. */
  iso3166: string;
  /** ISO 3166-1 alpha-3. */
  iso3166Alpha3: string;
  /** ISO 3166-1 numeric / UN M49. Null when ISO has not assigned one (Kosovo). */
  iso3166Numeric: string | null;
  /** Exceptionally reserved ISO 3166-1 alpha-2 (UK). */
  iso3166Reserved: string | null;
  /** FIFA association code. Null when FIFA has no country-level code. */
  fifa: string | null;
  /** IOC code. */
  ioc: string | null;
  labelDa: string;
  labelEn: string;
  aliases?: readonly string[];
};

export const EUROPEAN_COUNTRIES: readonly EuropeanCountry[] = [
  {
    iso3166: "AL",
    iso3166Alpha3: "ALB",
    iso3166Numeric: "008",
    iso3166Reserved: null,
    fifa: "ALB",
    ioc: "ALB",
    labelDa: "Albanien",
    labelEn: "Albania",
  },
  {
    iso3166: "AD",
    iso3166Alpha3: "AND",
    iso3166Numeric: "020",
    iso3166Reserved: null,
    fifa: "AND",
    ioc: "AND",
    labelDa: "Andorra",
    labelEn: "Andorra",
  },
  {
    iso3166: "AT",
    iso3166Alpha3: "AUT",
    iso3166Numeric: "040",
    iso3166Reserved: null,
    fifa: "AUT",
    ioc: "AUT",
    labelDa: "Østrig",
    labelEn: "Austria",
  },
  {
    iso3166: "BY",
    iso3166Alpha3: "BLR",
    iso3166Numeric: "112",
    iso3166Reserved: null,
    fifa: "BLR",
    ioc: "BLR",
    labelDa: "Belarus",
    labelEn: "Belarus",
    aliases: ["Hviderusland"],
  },
  {
    iso3166: "BE",
    iso3166Alpha3: "BEL",
    iso3166Numeric: "056",
    iso3166Reserved: null,
    fifa: "BEL",
    ioc: "BEL",
    labelDa: "Belgien",
    labelEn: "Belgium",
  },
  {
    iso3166: "BA",
    iso3166Alpha3: "BIH",
    iso3166Numeric: "070",
    iso3166Reserved: null,
    fifa: "BIH",
    ioc: "BIH",
    labelDa: "Bosnien-Hercegovina",
    labelEn: "Bosnia and Herzegovina",
  },
  {
    iso3166: "BG",
    iso3166Alpha3: "BGR",
    iso3166Numeric: "100",
    iso3166Reserved: null,
    fifa: "BUL",
    ioc: "BUL",
    labelDa: "Bulgarien",
    labelEn: "Bulgaria",
  },
  {
    iso3166: "HR",
    iso3166Alpha3: "HRV",
    iso3166Numeric: "191",
    iso3166Reserved: null,
    fifa: "CRO",
    ioc: "CRO",
    labelDa: "Kroatien",
    labelEn: "Croatia",
  },
  {
    iso3166: "CY",
    iso3166Alpha3: "CYP",
    iso3166Numeric: "196",
    iso3166Reserved: null,
    fifa: "CYP",
    ioc: "CYP",
    labelDa: "Cypern",
    labelEn: "Cyprus",
  },
  {
    iso3166: "CZ",
    iso3166Alpha3: "CZE",
    iso3166Numeric: "203",
    iso3166Reserved: null,
    fifa: "CZE",
    ioc: "CZE",
    labelDa: "Tjekkiet",
    labelEn: "Czechia",
    aliases: ["Czech Republic"],
  },
  {
    iso3166: "DK",
    iso3166Alpha3: "DNK",
    iso3166Numeric: "208",
    iso3166Reserved: null,
    fifa: "DEN",
    ioc: "DEN",
    labelDa: "Danmark",
    labelEn: "Denmark",
  },
  {
    iso3166: "EE",
    iso3166Alpha3: "EST",
    iso3166Numeric: "233",
    iso3166Reserved: null,
    fifa: "EST",
    ioc: "EST",
    labelDa: "Estland",
    labelEn: "Estonia",
  },
  {
    iso3166: "FI",
    iso3166Alpha3: "FIN",
    iso3166Numeric: "246",
    iso3166Reserved: null,
    fifa: "FIN",
    ioc: "FIN",
    labelDa: "Finland",
    labelEn: "Finland",
  },
  {
    iso3166: "FR",
    iso3166Alpha3: "FRA",
    iso3166Numeric: "250",
    iso3166Reserved: null,
    fifa: "FRA",
    ioc: "FRA",
    labelDa: "Frankrig",
    labelEn: "France",
  },
  {
    iso3166: "DE",
    iso3166Alpha3: "DEU",
    iso3166Numeric: "276",
    iso3166Reserved: null,
    fifa: "GER",
    ioc: "GER",
    labelDa: "Tyskland",
    labelEn: "Germany",
  },
  {
    iso3166: "GR",
    iso3166Alpha3: "GRC",
    iso3166Numeric: "300",
    iso3166Reserved: null,
    fifa: "GRE",
    ioc: "GRE",
    labelDa: "Grækenland",
    labelEn: "Greece",
  },
  {
    iso3166: "HU",
    iso3166Alpha3: "HUN",
    iso3166Numeric: "348",
    iso3166Reserved: null,
    fifa: "HUN",
    ioc: "HUN",
    labelDa: "Ungarn",
    labelEn: "Hungary",
  },
  {
    iso3166: "IS",
    iso3166Alpha3: "ISL",
    iso3166Numeric: "352",
    iso3166Reserved: null,
    fifa: "ISL",
    ioc: "ISL",
    labelDa: "Island",
    labelEn: "Iceland",
  },
  {
    iso3166: "IE",
    iso3166Alpha3: "IRL",
    iso3166Numeric: "372",
    iso3166Reserved: null,
    fifa: "IRL",
    ioc: "IRL",
    labelDa: "Irland",
    labelEn: "Ireland",
  },
  {
    iso3166: "IT",
    iso3166Alpha3: "ITA",
    iso3166Numeric: "380",
    iso3166Reserved: null,
    fifa: "ITA",
    ioc: "ITA",
    labelDa: "Italien",
    labelEn: "Italy",
  },
  {
    iso3166: "XK",
    iso3166Alpha3: "XKX",
    iso3166Numeric: null,
    iso3166Reserved: null,
    fifa: "KVX",
    ioc: "KOS",
    labelDa: "Kosovo",
    labelEn: "Kosovo",
  },
  {
    iso3166: "LV",
    iso3166Alpha3: "LVA",
    iso3166Numeric: "428",
    iso3166Reserved: null,
    fifa: "LVA",
    ioc: "LAT",
    labelDa: "Letland",
    labelEn: "Latvia",
  },
  {
    iso3166: "LI",
    iso3166Alpha3: "LIE",
    iso3166Numeric: "438",
    iso3166Reserved: null,
    fifa: "LIE",
    ioc: "LIE",
    labelDa: "Liechtenstein",
    labelEn: "Liechtenstein",
  },
  {
    iso3166: "LT",
    iso3166Alpha3: "LTU",
    iso3166Numeric: "440",
    iso3166Reserved: null,
    fifa: "LTU",
    ioc: "LTU",
    labelDa: "Litauen",
    labelEn: "Lithuania",
  },
  {
    iso3166: "LU",
    iso3166Alpha3: "LUX",
    iso3166Numeric: "442",
    iso3166Reserved: null,
    fifa: "LUX",
    ioc: "LUX",
    labelDa: "Luxembourg",
    labelEn: "Luxembourg",
  },
  {
    iso3166: "MT",
    iso3166Alpha3: "MLT",
    iso3166Numeric: "470",
    iso3166Reserved: null,
    fifa: "MLT",
    ioc: "MLT",
    labelDa: "Malta",
    labelEn: "Malta",
  },
  {
    iso3166: "MD",
    iso3166Alpha3: "MDA",
    iso3166Numeric: "498",
    iso3166Reserved: null,
    fifa: "MDA",
    ioc: "MDA",
    labelDa: "Moldova",
    labelEn: "Moldova",
  },
  {
    iso3166: "MC",
    iso3166Alpha3: "MCO",
    iso3166Numeric: "492",
    iso3166Reserved: null,
    fifa: null,
    ioc: "MON",
    labelDa: "Monaco",
    labelEn: "Monaco",
  },
  {
    iso3166: "ME",
    iso3166Alpha3: "MNE",
    iso3166Numeric: "499",
    iso3166Reserved: null,
    fifa: "MNE",
    ioc: "MNE",
    labelDa: "Montenegro",
    labelEn: "Montenegro",
  },
  {
    iso3166: "NL",
    iso3166Alpha3: "NLD",
    iso3166Numeric: "528",
    iso3166Reserved: null,
    fifa: "NED",
    ioc: "NED",
    labelDa: "Nederlandene",
    labelEn: "Netherlands",
    aliases: ["Holland"],
  },
  {
    iso3166: "MK",
    iso3166Alpha3: "MKD",
    iso3166Numeric: "807",
    iso3166Reserved: null,
    fifa: "MKD",
    ioc: "MKD",
    labelDa: "Nordmakedonien",
    labelEn: "North Macedonia",
  },
  {
    iso3166: "NO",
    iso3166Alpha3: "NOR",
    iso3166Numeric: "578",
    iso3166Reserved: null,
    fifa: "NOR",
    ioc: "NOR",
    labelDa: "Norge",
    labelEn: "Norway",
  },
  {
    iso3166: "PL",
    iso3166Alpha3: "POL",
    iso3166Numeric: "616",
    iso3166Reserved: null,
    fifa: "POL",
    ioc: "POL",
    labelDa: "Polen",
    labelEn: "Poland",
  },
  {
    iso3166: "PT",
    iso3166Alpha3: "PRT",
    iso3166Numeric: "620",
    iso3166Reserved: null,
    fifa: "POR",
    ioc: "POR",
    labelDa: "Portugal",
    labelEn: "Portugal",
  },
  {
    iso3166: "RO",
    iso3166Alpha3: "ROU",
    iso3166Numeric: "642",
    iso3166Reserved: null,
    fifa: "ROU",
    ioc: "ROU",
    labelDa: "Rumænien",
    labelEn: "Romania",
  },
  {
    iso3166: "RU",
    iso3166Alpha3: "RUS",
    iso3166Numeric: "643",
    iso3166Reserved: null,
    fifa: "RUS",
    ioc: "RUS",
    labelDa: "Rusland",
    labelEn: "Russia",
  },
  {
    iso3166: "SM",
    iso3166Alpha3: "SMR",
    iso3166Numeric: "674",
    iso3166Reserved: null,
    fifa: "SMR",
    ioc: "SMR",
    labelDa: "San Marino",
    labelEn: "San Marino",
  },
  {
    iso3166: "RS",
    iso3166Alpha3: "SRB",
    iso3166Numeric: "688",
    iso3166Reserved: null,
    fifa: "SRB",
    ioc: "SRB",
    labelDa: "Serbien",
    labelEn: "Serbia",
  },
  {
    iso3166: "SK",
    iso3166Alpha3: "SVK",
    iso3166Numeric: "703",
    iso3166Reserved: null,
    fifa: "SVK",
    ioc: "SVK",
    labelDa: "Slovakiet",
    labelEn: "Slovakia",
  },
  {
    iso3166: "SI",
    iso3166Alpha3: "SVN",
    iso3166Numeric: "705",
    iso3166Reserved: null,
    fifa: "SVN",
    ioc: "SLO",
    labelDa: "Slovenien",
    labelEn: "Slovenia",
  },
  {
    iso3166: "ES",
    iso3166Alpha3: "ESP",
    iso3166Numeric: "724",
    iso3166Reserved: null,
    fifa: "ESP",
    ioc: "ESP",
    labelDa: "Spanien",
    labelEn: "Spain",
  },
  {
    iso3166: "SE",
    iso3166Alpha3: "SWE",
    iso3166Numeric: "752",
    iso3166Reserved: null,
    fifa: "SWE",
    ioc: "SWE",
    labelDa: "Sverige",
    labelEn: "Sweden",
  },
  {
    iso3166: "CH",
    iso3166Alpha3: "CHE",
    iso3166Numeric: "756",
    iso3166Reserved: null,
    fifa: "SUI",
    ioc: "SUI",
    labelDa: "Schweiz",
    labelEn: "Switzerland",
  },
  {
    iso3166: "TR",
    iso3166Alpha3: "TUR",
    iso3166Numeric: "792",
    iso3166Reserved: null,
    fifa: "TUR",
    ioc: "TUR",
    labelDa: "Tyrkiet",
    labelEn: "Türkiye",
    aliases: ["Turkey"],
  },
  {
    iso3166: "UA",
    iso3166Alpha3: "UKR",
    iso3166Numeric: "804",
    iso3166Reserved: null,
    fifa: "UKR",
    ioc: "UKR",
    labelDa: "Ukraine",
    labelEn: "Ukraine",
  },
  {
    iso3166: "GB",
    iso3166Alpha3: "GBR",
    iso3166Numeric: "826",
    iso3166Reserved: "UK",
    fifa: null,
    ioc: "GBR",
    labelDa: "Storbritannien",
    labelEn: "United Kingdom",
    aliases: ["UK", "England", "Great Britain", "Britain"],
  },
  {
    iso3166: "VA",
    iso3166Alpha3: "VAT",
    iso3166Numeric: "336",
    iso3166Reserved: null,
    fifa: null,
    ioc: null,
    labelDa: "Vatikanstaten",
    labelEn: "Vatican City",
  },
] as const;

const BY_ISO3166: ReadonlyMap<string, EuropeanCountry> = new Map(
  EUROPEAN_COUNTRIES.map((country) => [country.iso3166, country]),
);

export function europeanCountryByIso3166(iso3166: string): EuropeanCountry | undefined {
  return BY_ISO3166.get(iso3166.toUpperCase());
}

export function countryCodesForIso3166(iso3166: string): {
  iso3166Alpha3: string | null;
  iso3166Numeric: string | null;
  iso3166Reserved: string | null;
  fifa: string | null;
  ioc: string | null;
} {
  const match = europeanCountryByIso3166(iso3166);
  return {
    iso3166Alpha3: match?.iso3166Alpha3 ?? null,
    iso3166Numeric: match?.iso3166Numeric ?? null,
    iso3166Reserved: match?.iso3166Reserved ?? null,
    fifa: match?.fifa ?? null,
    ioc: match?.ioc ?? null,
  };
}
