#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/harness/.env"

banner "KIT-53 — PI worker kit-harness (Hetzner CX33)"

stage "Confirm the box (already created)"
say "This wizard does not create the VPS. Inventory lives in harness/host.md."
note "name: kit-harness   id: 416348660   sku: CX33   city: Helsinki"
note "IPv4: 62.238.125.114   ssh: ssh kit-harness"
step "Do not install the product PaaS panel on this box."
step "Do not put DATABASE_URL on this box."
pause "Press Enter if that matches the Hetzner overview."

stage "Firewall 22 / 80 / 443"
open_url "https://console.hetzner.cloud/"
step "Open project → kit-harness → Firewalls."
step "Allow inbound TCP 22, 80, 443 from 0.0.0.0/0 (and ::/0 if IPv6 is on)."
pause "Press Enter when the firewall is applied."

stage "DNS harness.eskobar.dev"
open_url "https://dash.cloudflare.com/"
step "A record: harness.eskobar.dev → 62.238.125.114 (proxied or DNS-only is your call; webhook HMAC needs the origin)."
ask PI_WORKER_PUBLIC_HOST "Public hostname [Enter = harness.eskobar.dev]:"
if [[ -z "${PI_WORKER_PUBLIC_HOST:-}" ]]; then PI_WORKER_PUBLIC_HOST="harness.eskobar.dev"; fi
write_env PI_WORKER_PUBLIC_HOST "$PI_WORKER_PUBLIC_HOST"
pause "Press Enter when the A record exists."

stage "Worker secrets (names in .env.example — values never git)"
say "Paste values for the CX33 process. Empty skips. DATABASE_URL must stay unset."
ask_secret CURSOR_API_KEY "Cursor SDK API key (Dashboard → Integrations / API Keys, not Anthropic):"
ask_secret LINEAR_CLI_API_KEY "Linear CLI key for the worker (not the bootstrap LINEAR_API_KEY):"
ask_secret LINEAR_WEBHOOK_SECRET "Linear Issue webhook HMAC secret:"
ask_secret GH_TOKEN "GitHub token for gh:"
ask_secret LINEAR_PI_APP_USER_ID "Pi Linear app user UUID (KIT-58, not a token, not Cursor):"
ask_secret OPENROUTER_API_KEY "OpenRouter key for Scout and Gate (tencent/hy3). Value stays on kit-harness:"
[[ -n "${CURSOR_API_KEY:-}" ]] && write_env CURSOR_API_KEY "$CURSOR_API_KEY"
[[ -n "${LINEAR_CLI_API_KEY:-}" ]] && write_env LINEAR_CLI_API_KEY "$LINEAR_CLI_API_KEY"
[[ -n "${LINEAR_WEBHOOK_SECRET:-}" ]] && write_env LINEAR_WEBHOOK_SECRET "$LINEAR_WEBHOOK_SECRET"
[[ -n "${GH_TOKEN:-}" ]] && write_env GH_TOKEN "$GH_TOKEN"
[[ -n "${LINEAR_PI_APP_USER_ID:-}" ]] && write_env LINEAR_PI_APP_USER_ID "$LINEAR_PI_APP_USER_ID"
[[ -n "${OPENROUTER_API_KEY:-}" ]] && write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
write_env LINEAR_CLI_VERSION "2.5.0"
pause "Press Enter to continue."

stage "Docker Compose on kit-harness"
say "SSH as root with ~/.ssh/hetzner_key. Install Docker Engine + compose plugin if missing."
note "ssh kit-harness"
step "Clone KitCollective/kit-collective (development, then this branch) into /opt/kit-collective."
step "Copy worker keys into /opt/kit-collective/harness/.env — omit DATABASE_URL."
step "cd /opt/kit-collective/harness && docker compose up -d --build"
pause "Press Enter when compose is up."

stage "Healthcheck evidence"
say "From your laptop:"
note "curl -sS https://harness.eskobar.dev/health"
step "Expect JSON {\"ok\":true,\"planner\":\"active\"}."
step "Paste that curl output as Evidence on KIT-53. Keep the issue ready-for-human until it is there."
pause "Press Enter after curl succeeds."

finish
printf '  Inventory: harness/host.md\n'
printf '  SSH: ssh kit-harness\n'
printf '  Re-run: bash harness/cx33-wizard.sh\n\n'
