#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# KitCollective repo root (this file lives in .scratch/pi/).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

# Documented placeholder until KIT-53 CX23 has a public HTTPS URL.
PI_AGENT_SESSION_WEBHOOK_PLACEHOLDER="https://example.com/kit-58-pi-agent-session-until-cx23"
PI_OAUTH_CALLBACK="http://127.0.0.1:8765/linear/oauth/callback"

# lookup_pi_user_id — optional: use the existing bootstrap LINEAR_API_KEY to
# find the workspace app user named Pi. Prints the UUID or empty. Never prints the key.
lookup_pi_user_id() {
  local key json
  key="$(_existing LINEAR_API_KEY || true)"
  [[ -n "$key" ]] || return 0
  command -v curl >/dev/null 2>&1 || return 0
  json="$(
    curl -sS "https://api.linear.app/graphql" \
      -H "Content-Type: application/json" \
      -H "Authorization: $key" \
      --data '{"query":"{ users(filter: { name: { eq: \"Pi\" } }) { nodes { id name displayName } } }"}' \
      || true
  )"
  # Prefer python3 for JSON; fall back to a conservative sed if needed.
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import json,sys; d=json.load(sys.stdin); n=d.get("data",{}).get("users",{}).get("nodes") or []; print(n[0]["id"] if n else "")' <<<"$json" 2>/dev/null || true
  fi
}

banner "KIT-58 — Pi Linear OAuth app (actor=app)"

# ── 1. Create the OAuth application ───────────────────────────────────────
stage "Create the Linear OAuth application"
say "Workspace admin only (Nicklas). Do not set Linear Agent to Cursor on this issue."
say "Name must be unique in Assignee → Agents. Cursor and Linear already occupy those slots — use Pi."
open_url "https://linear.app/settings/api/applications/new"
step "If you are not on New application: Settings → API → Applications → New application."
step "Application name: Pi"
step "Description: KitCollective factory harness (Hetzner Pi). Wake is Issue status; Agent session events are display/ack only."
step "Callback URL (required by the form; CX23 is not up yet): $PI_OAUTH_CALLBACK"
step "Icon: any mark that is not Cursor's arrow and not Linear's chevron. Unique in Assignee → Agents."
pause "Press Enter when the application exists (you can still edit it in the next stages)."

# ── 2. actor=app + assignable/mentionable ─────────────────────────────────
stage "actor=app + app:assignable + app:mentionable"
say "These scopes are how Pi appears as a delegate/mention without replacing the human assignee."
step "On the application, enable Client credentials tokens if that toggle exists (server-to-server app actor)."
step "Copy Client ID and Client secret. The secret is shown once — paste it here, not into git."
ask LINEAR_PI_CLIENT_ID "Paste the Client ID:"
ask_secret LINEAR_PI_CLIENT_SECRET "Paste the Client secret (hidden):"
if [[ -n "${LINEAR_PI_CLIENT_ID:-}" ]]; then
  write_env LINEAR_PI_CLIENT_ID "$LINEAR_PI_CLIENT_ID"
fi
if [[ -n "${LINEAR_PI_CLIENT_SECRET:-}" ]]; then
  write_env LINEAR_PI_CLIENT_SECRET "$LINEAR_PI_CLIENT_SECRET"
fi
say "Install as actor=app (admin). Typical authorize URL (replace CLIENT_ID):"
note "https://linear.app/oauth/authorize?response_type=code&client_id=CLIENT_ID&redirect_uri=http%3A%2F%2F127.0.0.1%3A8765%2Flinear%2Foauth%2Fcallback&scope=read,write,app:assignable,app:mentionable&actor=app"
step "If the application page has Authorize / Install, use that. Confirm actor is app, not user."
step "Grant team access to KIT if a team picker is shown."
warn "Do not request the admin OAuth scope. actor=app cannot combine with admin."
pause "Press Enter when Pi is installed on the KitCollective workspace as actor=app."

# ── 3. Agent session event webhooks ───────────────────────────────────────
stage "Agent session event webhooks"
say "KIT-53 CX23 is not up yet. Use the documented placeholder. KIT-53 replaces it with the public HTTPS URL."
say "Placeholder: $PI_AGENT_SESSION_WEBHOOK_PLACEHOLDER"
open_url "https://linear.app/settings/api"
step "Open the Pi application → Webhooks (or the webhook block on the application form)."
step "Enable webhooks. At the bottom, select Agent session events (Linear's agent-session category)."
step "Webhook URL: paste the placeholder unless you already have the CX23 URL."
ask LINEAR_PI_AGENT_SESSION_WEBHOOK_URL "Webhook URL [Enter = placeholder]:"
if [[ -z "${LINEAR_PI_AGENT_SESSION_WEBHOOK_URL:-}" ]]; then
  LINEAR_PI_AGENT_SESSION_WEBHOOK_URL="$PI_AGENT_SESSION_WEBHOOK_PLACEHOLDER"
fi
write_env LINEAR_PI_AGENT_SESSION_WEBHOOK_URL "$LINEAR_PI_AGENT_SESSION_WEBHOOK_URL"
step "Copy the webhook signing secret if Linear shows one (not the OAuth client secret)."
ask_secret LINEAR_PI_WEBHOOK_SECRET "Paste the webhook signing secret (hidden, Enter skips):"
if [[ -n "${LINEAR_PI_WEBHOOK_SECRET:-}" ]]; then
  write_env LINEAR_PI_WEBHOOK_SECRET "$LINEAR_PI_WEBHOOK_SECRET"
fi
warn "Issue status webhooks (factory wake) are a different subscription. Do not point those at a placeholder that will 404 in a loop if you already have a working Issue webhook."
pause "Press Enter when Agent session events are enabled on this app."

# ── 4. Confirm unique in Assignee → Agents ────────────────────────────────
stage "Unique in Assignee → Agents"
say "Pi must be distinguishable from Cursor and Linear on the issue Agent field."
step "Open any KIT issue (not this ticket's Agent field — leave Agent empty / not Cursor)."
step "Assignee → Agents (or the Agent / delegate picker). Confirm Pi is listed with the icon you set."
step "Screenshot that picker. Attach it on KIT-58 Evidence (this wizard does not upload to Linear)."
pause "Press Enter after the screenshot is captured."

# ── 5. App user id (name in git, value only in .env) ──────────────────────
stage "Record LINEAR_PI_APP_USER_ID"
say "This is the workspace app user's UUID, not an API token. It goes in gitignored .env only."
say ".env.example already lists the name LINEAR_PI_APP_USER_ID= with an empty value."
FOUND_ID="$(lookup_pi_user_id || true)"
if [[ -n "${FOUND_ID:-}" ]]; then
  say "Bootstrap LINEAR_API_KEY found a user named Pi: $FOUND_ID"
  if confirm "Write that id to .env as LINEAR_PI_APP_USER_ID"; then
    LINEAR_PI_APP_USER_ID="$FOUND_ID"
  fi
fi
if [[ -z "${LINEAR_PI_APP_USER_ID:-}" ]]; then
  step "Settings → Members (filter agents) or GraphQL: { users(filter: { name: { eq: \"Pi\" } }) { nodes { id name } } }"
  step "Or open Pi's profile and copy the user UUID."
  ask LINEAR_PI_APP_USER_ID "Paste the Pi app user UUID:"
fi
if [[ -n "${LINEAR_PI_APP_USER_ID:-}" ]]; then
  write_env LINEAR_PI_APP_USER_ID "$LINEAR_PI_APP_USER_ID"
else
  warn "No app user id captured. Re-run this stage after the install is visible in Members."
  SKIPPED+=("LINEAR_PI_APP_USER_ID")
fi
pause "Press Enter to continue."

# ── 6. Do not start jobs from Assignee-click ──────────────────────────────
stage "No Pi jobs from Assignee-click"
say "KIT-58 stops at the Linear application. KIT-59 owns Agent session ack. KIT-52 owns Issue-status wake."
step "Do not click Assignee → Pi on a live issue to 'try' the worker. CX23 is not up; that would only create a session."
step "Leave KIT-58 Linear Agent empty. Never set it to Cursor."
step "Attach the Agents-picker screenshot on https://linear.app/kitcollective/issue/KIT-58"
pause "Press Enter to finish. Status stays Implementing until that screenshot is on the issue."

finish
printf '  Next: attach the Assignee → Agents screenshot on KIT-58 Evidence.\n'
printf '  Re-run: bash .scratch/pi/wizard.sh\n'
printf '  Do not commit .env. Secret names live in .env.example.\n\n'
