/**
 * PI implement context generator — stale detection and mobile fixture coverage.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { selectImplementContext } from "../../harness/implement-context.mjs";
import {
  buildImplementContextMarkdown,
  buildPiAgentMarkdown,
  extractImplementLoopExcerpt,
  generatePiImplementContext,
  PI_AGENT_MAP,
} from "../generate-pi-implement-context.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

test("extractImplementLoopExcerpt includes unattended run and pre-review gate", () => {
  const skill = readFileSync(join(ROOT, ".cursor/skills/implement/SKILL.md"), "utf8");
  const excerpt = extractImplementLoopExcerpt(skill);
  assert.match(excerpt, /## Unattended run/);
  assert.match(excerpt, /## Pre-review gate/);
  assert.doesNotMatch(excerpt, /## Domain helpers/);
});

test("buildImplementContextMarkdown includes always rules, skills, and PI overlays", () => {
  const md = buildImplementContextMarkdown();
  assert.match(md, /Generated by scripts\/generate-pi-implement-context\.mjs/);
  assert.match(md, /sources-sha256:/);
  assert.match(md, /\.cursor\/rules\/write-scope\.mdc/);
  assert.match(md, /\.cursor\/skills\/tdd\/SKILL\.md/);
  assert.match(md, /loop excerpt/);
  assert.match(md, /GitHub Actions only/);
  assert.match(md, /LINEAR_CLI_API_KEY/);
});

test("PI agent wrappers pin Composer so Pi does not use the OpenRouter default", () => {
  const nest = buildPiAgentMarkdown(PI_AGENT_MAP.find((item) => item.pi === "nest"));
  assert.match(nest, /Modular monolith in `apps\/api`/);
  assert.match(nest, /inheritProjectContext: false/);
  assert.match(nest, /^model:\s+cursor\/composer-2\.5\s*$/m);
  assert.doesNotMatch(nest, /openrouter|kimi|moonshot|tencent\/hy[34]/i);
  const devops = buildPiAgentMarkdown(PI_AGENT_MAP.find((item) => item.pi === "devops"));
  assert.match(devops, /GitHub Actions/);
  assert.match(devops, /^model:\s+cursor\/composer-2\.5\s*$/m);
});

test("mobile selector still includes ui-ux, expo, and tdd after generated base split", () => {
  const ctx = selectImplementContext({
    writeScope: "apps/mobile/**",
    labels: ["mobile"],
    cheapRetry: false,
  });
  assert.deepEqual(ctx.requiredHelpers, ["expo", "ui-ux"]);
  assert.ok(ctx.skills.includes(".cursor/skills/tdd/SKILL.md"));
  assert.ok(ctx.skills.includes(".cursor/skills/expo/expo-overview/SKILL.md"));
});

test("generatePiImplementContext --check passes when outputs are current", () => {
  generatePiImplementContext();
  const result = generatePiImplementContext({ write: false });
  assert.equal(result.changed, false);
});
