#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

_disk_avail_kb() {
  if [[ -d /System/Volumes/Data ]]; then
    df -k /System/Volumes/Data | awk 'NR==2 {print $4}'
  else
    df -k / | awk 'NR==2 {print $4}'
  fi
}

_disk_avail_human() {
  if [[ -d /System/Volumes/Data ]]; then
    df -h /System/Volumes/Data | awk 'NR==2 {print $4}'
  else
    df -h / | awk 'NR==2 {print $4}'
  fi
}

banner "KitCollective — Expo CLI (local, no EAS cloud build)"

# ── 1. Disk space ─────────────────────────────────────────────────────────
stage "Free disk space"
say "Metro and pnpm need several GB. This Mac was at 100% when we tried Expo CLI."
note "Available right now: $(_disk_avail_human)"
step "Opening DaisyDisk. Delete large unused files until at least ~5 GB is free."
step "Docker images and ~/Library/Caches are usual wins. Do not delete this git repo."
if [[ -d "$HOME/Applications/DaisyDisk.app" ]]; then
  open "$HOME/Applications/DaisyDisk.app" >/dev/null 2>&1 || true
elif [[ -d /Applications/DaisyDisk.app ]]; then
  open /Applications/DaisyDisk.app >/dev/null 2>&1 || true
fi
pause "Press Enter when disk cleanup is done."
avail="$(_disk_avail_kb)"
note "Available now: $(_disk_avail_human)"
if [[ "${avail:-0}" -lt 3000000 ]]; then
  warn "Still under ~3 GB free. pnpm install / Metro will likely fail with ENOSPC."
  SKIPPED+=("Free more disk (need ~5 GB) before pnpm install")
else
  say "Disk looks usable for install + Metro."
fi

# ── 2. Expo account via eas CLI ───────────────────────────────────────────
stage "Log in to Expo with eas CLI"
say "The EAS project is already linked: owner kitcollective, id ddddf92b-e7cd-4ec5-b07c-643106041550."
say "eas is installed globally. We are not running a cloud build — login just binds the CLI."
if ! command -v eas >/dev/null 2>&1; then
  warn "eas not on PATH. Install: npm install --global eas-cli"
  SKIPPED+=("Install eas-cli then re-run this stage")
  pause "Press Enter to continue anyway."
else
  who_out="$(eas whoami 2>&1 || true)"
  if [[ "$who_out" == *"Not logged in"* ]] || [[ "$who_out" == *"not logged in"* ]]; then
    open_url "https://expo.dev/login"
    step "If you have no account: Sign up. Use the kitcollective org you already own."
    step "Back here: email + password (or SSO) at the eas login prompt. 2FA in the browser if asked."
    say "Starting eas login (interactive)…"
    eas login || {
      warn "eas login failed or was cancelled."
      SKIPPED+=("eas login")
    }
  else
    say "Already logged in: $who_out"
  fi
fi

# ── 3. How to open the app ────────────────────────────────────────────────
stage "Simulator vs Expo Go on iPhone"
say "xcode-select currently points at Command Line Tools, not Xcode.app."
say "There is no /Applications/Xcode.app on this Mac, so iOS Simulator is not available."
if [[ -d /Applications/Xcode.app ]]; then
  say "Xcode.app found. After this wizard you can: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer"
  say "then in apps/mobile: pnpm exec expo start --ios"
else
  warn "Install Xcode from the App Store later if you want the Simulator."
  step "Today: install Expo Go on your iPhone from the App Store, same Wi-Fi as this Mac."
  open_url "https://apps.apple.com/app/expo-go/id982107779"
fi
pause "Press Enter when you know which device you will use (Expo Go on phone, or Simulator after Xcode)."

# ── 4. API URL ────────────────────────────────────────────────────────────
stage "EXPO_PUBLIC_API_URL"
say "The app talks to Nest. Coolify kit-api is down — use Nest on this Mac (port 3000)."
say "iOS Simulator can use localhost. Expo Go on a physical iPhone cannot — it needs your LAN IP."
lan_ip="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
if [[ -n "$lan_ip" ]]; then
  note "This Mac's LAN IP (en0/en1): $lan_ip"
fi
if confirm "Are you opening the app in Expo Go on a physical iPhone?"; then
  if [[ -z "$lan_ip" ]]; then
    warn "Could not detect LAN IP. Find it: System Settings → Wi-Fi → Details → IP address."
    ask EXPO_PUBLIC_API_URL "API URL (http://YOUR_LAN_IP:3000):"
  else
    EXPO_PUBLIC_API_URL="http://${lan_ip}:3000"
    say "Using $EXPO_PUBLIC_API_URL"
  fi
else
  EXPO_PUBLIC_API_URL="http://localhost:3000"
  say "Using $EXPO_PUBLIC_API_URL"
fi
if [[ -z "${EXPO_PUBLIC_API_URL:-}" ]]; then
  warn "No API URL entered."
  SKIPPED+=("Set EXPO_PUBLIC_API_URL in apps/mobile/.env")
else
  ENV_FILE="$REPO_ROOT/apps/mobile/.env"
  write_env EXPO_PUBLIC_API_URL "$EXPO_PUBLIC_API_URL"
  ENV_FILE="$REPO_ROOT/.env"
fi

# ── 5. Nest boot secret ───────────────────────────────────────────────────
stage "JWT_SECRET for local Nest"
say "Identity will not boot without JWT_SECRET. DATABASE_URL is already in root .env."
say "This value stays in local .env only — not GitHub, not Expo, not the client bundle."
ENV_FILE="$REPO_ROOT/.env"
if [[ -n "$(_existing JWT_SECRET || true)" ]]; then
  say "JWT_SECRET is already set in .env — leaving it."
else
  if confirm "Generate a random local JWT_SECRET now?"; then
    JWT_SECRET="$(openssl rand -hex 32)"
    write_env JWT_SECRET "$JWT_SECRET"
  else
    ask_secret JWT_SECRET "Paste JWT_SECRET (hidden):"
    if [[ -n "${JWT_SECRET:-}" ]]; then
      write_env JWT_SECRET "$JWT_SECRET"
    else
      warn "Skipped — Nest will refuse to start."
      SKIPPED+=("Set JWT_SECRET in .env")
    fi
  fi
fi
ENV_FILE="$REPO_ROOT/.env"

# ── 6. Install + commands to connect ──────────────────────────────────────
stage "pnpm install and how to connect"
say "Run these from the repo root in two terminals after this wizard exits."
note "Terminal A — Nest:"
say "  set -a && source .env && set +a"
say "  pnpm install"
say "  pnpm --filter @kit/api build && pnpm --filter @kit/api start"
note "Terminal B — Expo CLI (Expo Go, not a custom dev client):"
say "  pnpm --filter @kit/mobile start"
step "When Metro prints a QR code: open it with the Expo Go app (iPhone) or press i if a Simulator exists."
step "Confirm the bundler URL in Expo Go matches this Mac. First load can take a minute."
pause "Press Enter to finish. Then run the two terminals yourself."

finish

printf '  Next: Terminal A = Nest, Terminal B = pnpm --filter @kit/mobile start\n'
printf '  Expo Go on iPhone if there is no Xcode.app. Re-run this wizard any time.\n\n'
